plugins:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  Exclude:
    - "spec/statistical_accuracy_spec.rb"
    - "vendor/**/*.*"

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Naming/FileName:
  Exclude:
    - "lib/enumerable-stats.rb"

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Max: 25

Metrics/ModuleLength:
  Max: 250

Metrics/AbcSize:
  Max: 100

Metrics/CyclomaticComplexity:
  Max: 20

Metrics/MethodLength:
  Max: 40

Metrics/PerceivedComplexity:
  Max: 20

Naming/VariableNumber:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Layout/LineLength:
  Max: 125
