plugins:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Naming/FileName:
  Exclude:
    - "lib/enumerable-stats.rb"

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Max: 25

Metrics/ModuleLength:
  Max: 250

Metrics/AbcSize:
  Max: 65

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/MethodLength:
  Max: 40

Metrics/PerceivedComplexity:
  Max: 15

Naming/VariableNumber:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false
