plugins:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Naming/FileName:
  Exclude:
    - "lib/enumerable-stats.rb"

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Max: 10

Metrics/ModuleLength:
  Max: 250

Metrics/AbcSize:
  Max: 50

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/MethodLength:
  Max: 25

Metrics/PerceivedComplexity:
  Max: 10
